/**
 * Platform-specific export utilities for compiled prompts.
 * Each platform has specific formatting requirements and constraints.
 */

import type { CompileResult } from "./types";

export interface PlatformExport {
  content: string;
  filename: string;
  warning?: string;
}

/**
 * ChatGPT Custom Instructions format.
 * Limited to 1500 characters per field (What would you like ChatGPT to know about you
 * to provide better responses? / How would you like ChatGPT to respond?).
 * We combine everything into a single instruction block.
 */
export function formatForChatGPT(result: CompileResult): PlatformExport {
  const content = result.markdown;
  const charLimit = 1500;
  
  let warning: string | undefined;
  if (content.length > charLimit) {
    warning = `⚠️ Content is ${content.length} characters, but ChatGPT custom instructions are limited to ${charLimit} characters. Consider selecting fewer fragments or using a more concise format.`;
  }

  return {
    content,
    filename: "chatgpt-instructions.txt",
    warning,
  };
}

/**
 * Claude Projects knowledge format.
 * Claude Projects can store up to ~100k characters of context.
 * We export as Markdown since Claude handles it natively.
 */
export function formatForClaude(result: CompileResult): PlatformExport {
  const content = `# Project Context

This prompt was compiled from ${result.manifest.selectedFragments.length} fragments using Prompt Primer.
Token count: ${result.manifest.tokenCount} / ${result.manifest.tokenBudget}

---

${result.markdown}

---

*Compiled at: ${result.manifest.compiledAt}*
*Output format: ${result.manifest.outputFormat}*`;

  return {
    content,
    filename: "claude-project-context.md",
  };
}

/**
 * GitHub Copilot instructions format.
 * Exports as .github/copilot-instructions.md for repository-level context.
 */
export function formatForCopilot(result: CompileResult): PlatformExport {
  const content = `# GitHub Copilot Instructions

${result.markdown}

---

<!-- 
  This file was generated by Prompt Primer
  Compiled at: ${result.manifest.compiledAt}
  Fragments: ${result.manifest.selectedFragments.map((f) => f.id).join(", ")}
  Token count: ${result.manifest.tokenCount}
-->`;

  return {
    content,
    filename: "copilot-instructions.md",
  };
}

/**
 * OpenAI API cURL command.
 * Generates a ready-to-run cURL command for testing with the OpenAI API.
 */
export function formatAsCurl(result: CompileResult): PlatformExport {
  const systemMessage = JSON.stringify(result.openAIMessage);
  const userMessage = JSON.stringify({
    role: "user",
    content: "Hello! I'm ready to work with you.",
  });

  const content = `#!/bin/bash
# OpenAI API cURL example
# Replace YOUR_API_KEY with your actual OpenAI API key

curl https://api.openai.com/v1/chat/completions \\
  -H "Content-Type: application/json" \\
  -H "Authorization: Bearer YOUR_API_KEY" \\
  -d '{
    "model": "gpt-4",
    "messages": [
      ${systemMessage},
      ${userMessage}
    ],
    "temperature": 0.7,
    "max_tokens": 2000
  }'

# Anthropic Claude API example (alternative)
# curl https://api.anthropic.com/v1/messages \\
#   -H "Content-Type: application/json" \\
#   -H "x-api-key: YOUR_API_KEY" \\
#   -H "anthropic-version: 2023-06-01" \\
#   -d '{
#     "model": "claude-3-5-sonnet-20241022",
#     "max_tokens": 4096,
#     "system": ${JSON.stringify(result.markdown)},
#     "messages": [
#       ${userMessage}
#     ]
#   }'
`;

  return {
    content,
    filename: "api-example.sh",
  };
}

/**
 * Export for VS Code .instructions.md format.
 * Used by GitHub Copilot in VS Code workspace root.
 */
export function formatForVSCode(result: CompileResult): PlatformExport {
  const content = `# VS Code Instructions

${result.markdown}

---

*Auto-generated from Prompt Primer*  
*Fragments: ${result.manifest.selectedFragments.map((f) => f.id).join(", ")}*  
*Token count: ${result.manifest.tokenCount}*`;

  return {
    content,
    filename: ".instructions.md",
  };
}

/**
 * All available platform exports.
 */
export const platformExports = {
  chatgpt: {
    label: "ChatGPT Custom Instructions",
    description: "Copy for ChatGPT custom instructions (1500 char limit)",
    format: formatForChatGPT,
  },
  claude: {
    label: "Claude Projects",
    description: "Copy for Claude Projects knowledge base",
    format: formatForClaude,
  },
  copilot: {
    label: "GitHub Copilot",
    description: "Export as .github/copilot-instructions.md",
    format: formatForCopilot,
  },
  vscode: {
    label: "VS Code Instructions",
    description: "Export as .instructions.md for workspace root",
    format: formatForVSCode,
  },
  curl: {
    label: "cURL API Example",
    description: "Download ready-to-run API example script",
    format: formatAsCurl,
  },
} as const;

export type PlatformKey = keyof typeof platformExports;
